import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import React from "react";
import { Theme } from "@radix-ui/themes";
import Header from "@/components/Header/Header";
import SideBar from "@/components/SideBar/SideBar";
import { AppWrapper } from "@/contexts/context";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Google Font Clone",
  description: "Generated by create next app",
  icons:
    "https://seeklogo.com/images/G/google-fonts-logo-185D843C0C-seeklogo.com.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Theme className="flex">
          <AppWrapper>
            <SideBar />
            <main className="container max-w-[1500px] px-8">
              <Header />
              {children}
            </main>
          </AppWrapper>
        </Theme>
      </body>
    </html>
  );
}
