import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import React from "react";
import { Theme } from "@radix-ui/themes";
import Navbar from "@/components/Navbar/Navbar";
import { AppWrapper } from "@/contexts/context";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <AppWrapper>
          <Theme className="flex flex-col items-center">
            <Navbar />
            {children}
          </Theme>
        </AppWrapper>
      </body>
    </html>
  );
}
