import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import React from "react";
import { Theme } from "@radix-ui/themes";
import Navbar from "@/components/Navbar/Navbar";
import SideBar from "@/components/SideBar/SideBar";
import { AppWrapper } from "@/contexts/context";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Google Font Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Theme className="flex">
          <AppWrapper>
            <SideBar />
            <main className="flex flex-col items-center">
              <Navbar />
              {children}
            </main>
          </AppWrapper>
        </Theme>
      </body>
    </html>
  );
}
